# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Camera' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Camera
  pod 'Alamofire', '~> 3.4'
  pod 'TanLT1Extensions'  

  target 'CameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CameraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
